# Site settings
title: Bjørn Fjukstad
email: bjornfjukstad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer at DIPS AS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fjukstad.github.io" # the base hostname & protocol for your site
twitter_username: fjukstad
github_username: fjukstad 

# Build settings
markdown: kramdown
