# Site settings
title: Bjørn Fjukstad
email: bjorn@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
   Ph. D. student in computer science at UiT - The Arctic University of Norway. 
  # working on interactive systems for exploring data from the Norwegian Women and Cancer (NOWAC) study. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fjukstad.github.io" # the base hostname & protocol for your site
twitter_username: fjukstad
github_username: fjukstad 

# Build settings
markdown: kramdown
